---
- name: 普通にloop
  hosts: all
  tasks:
    - debug:
        msg: "{{ item }}"
      loop: [0, 2, 4, 6, 8, 10]

- name: product filter
  hosts: all
  tasks:
    - debug:
        var: item
      loop: "{{ ['alice', 'bob'] | product(['client', 'employeedb', 'providerdb']) | list }}"

- name: loop_control label
  hosts: all
  tasks:
    - debug:
        msg: "{{ item.name }}"
      loop:
        - name: server1
          disks: 3gb
          ram: 15Gb
          network:
            nic01: 100Gb
            nic02: 10Gb
      loop_control:
        label: "{{ item.name }}"
      # ok: [localhost] => (item={u'disks': u'3gb', u'ram': u'15Gb', u'name': u'server1', u'network': {u'nic02': u'10Gb', u'nic01': u'100Gb'}})
      # が
      # ok: [localhost] => (item=server1)
      # になるよ！

- name: iroiro tamesuyo!
  hosts: all
  tasks:
    - name: zip filter
      debug:
        msg: "{{ list1 | zip(list2) | list }}"
      vars:
        - list1: [0, 1 ,2]
        - list2: [a, b, c]
    - name: map
      debug:
        msg: "{{ 'test_var' | regex_replace('$', '_suffix') }}"
    - name: map filter
      debug:
        msg: "{{ test | map('regex_replace', '$', '_suffix') | list }}"
      vars:
        - test:
            - test_var1
            - test_var2
            - test_var3

- name: block rescue
  debugger: never
  hosts: all
  tasks:
    - name: Handle the error
      block:
        - debug:
            msg: 'I execute normally'
        - name: i force a failure
          command: /bin/false
        - debug:
            msg: 'I never execute, due to the above task failing, :-('
      rescue:
        - debug:
            var: ansible_failed_task
    - name: next task (same play)!
      debug:
        msg: 'does next task be executed ?'

- name: block rescue 2
  hosts: all
  tasks:
    - name: next task (another play)
      debug:
        msg: 'does next task be executed ?'

- name: vault test
  hosts: all
  vars_files:
    - private.yml
  tasks:
    - debug:
        msg: "password = {{ password }}"
